---
- name: OSX Local Provisioner
  hosts: localhost
  sudo: no
  pre_tasks:
    - stat: path=~/.ssh
      register: ssh
  roles:
    # App Installations
    - brew
    - brew-cask

    # Configurations
    - git
    - go
    - vim
    - zsh
    - {
      role: ssh,
      when: not ssh.stat.exists
    }
